### PR TITLE
make gravity mostly universal (600)

### PR DESCRIPTION
**Pull request by TechnichalDoge**
this helps up projectile motion formulas, but this also probably warrants more testings to see if the velocities look right, i checked over it and didnt really see much that was an issue, but doing ingame tests are warranted.

### CODE REVIEW

**Comment by brandonsturgeon** [comment]
Closing because it's not a requested feature

**Comment by TechnichalDoge** [comment]
oof

**Comment by TechnichalDoge** [comment]
keep this closed

**Comment by TechnichalDoge** [comment]
The issue seems to be a combination of using the old system and having gravity set with hexwolf's artilleries, moreso than it being just the gravity

**Pull request closed without merging**
